import { CategoryType, TaskType, SubtaskType, TaskStatus, TrackerFrequency, ViewAsType } from "@/types/types";

const dummyChoresList: CategoryType[] = [
  {
    id: 1,
    title: "Morning Routine",
    description: "Start your day with these healthy habits",
    createdOn: new Date(),
    priority: 10,
    labels: ["Healthy", "Morning"],
    remark: "This is a morning routine category.",
    tasks: [
      {
        id: 1,
        title: "Wake up at 7:00 AM",
        status: "Not Started",
        description: "Start the day on time",
        subtasks: [
          {
            id: 11,
            title: "Set an intention for the day",
            status: "Not Started",
            description: "Think about your goals for the day",
            subtasks: [],
            priorityLabel: "Moderate",
            priority: 20,
            scheduled: { deploymentSchedule: new Date() },
            locked: false,
            flexible: false,
            track: { trackerId: 0, trackerTitle: "", trackerFrequency: "Daily" },
            createdOn: new Date(),
            expiresOn: new Date(),
            completedOn: undefined,
            viewAs: 'Status',
            SpecialLabels: ["Goal"],
            remark: '',
          },
          {
            id: 12,
            title: "Express gratitude",
            status: "Not Started",
            description: "Take a moment to be thankful",
            subtasks: [],
            priorityLabel: "Moderate",
            priority: 30,
            scheduled: { deploymentSchedule: new Date() },
            locked: false,
            flexible: false,
            track: { trackerId: 0, trackerTitle: "", trackerFrequency: "Daily" },
            createdOn: new Date(),
            expiresOn: new Date(),
            completedOn: undefined,
            viewAs: 'Checkbox',
            SpecialLabels: ["Gratitude"],
            remark: '',
          },
        ],
        priorityLabel: "Moderate",
        priority: 10,
        scheduled: { deploymentSchedule: new Date() },
        locked: false,
        flexible: false,
        track: { trackerId: 0, trackerTitle: "", trackerFrequency: "Daily" },
        createdOn: new Date(),
        expiresOn: new Date(),
        completedOn: undefined,
        viewAs: "Checkbox",
        SpecialLabels: ["Routine"],
        remark: "",
      },
      {
        id: 2,
        title: "Brush teeth",
        status: "Not Started",
        description: "Maintain oral hygiene",
        subtasks: [],
        priorityLabel: "Moderate",
        priority: 20,
        scheduled: { deploymentSchedule: new Date() },
        locked: false,
        flexible: false,
        track: { trackerId: 0, trackerTitle: "", trackerFrequency: "Daily" },
        createdOn: new Date(),
        expiresOn: new Date(),
        completedOn: undefined,
        viewAs: "Checkbox",
        SpecialLabels: ["Hygiene"],
        remark: "",
      },
      // ... other tasks
    ],
  },
  {
    id: 2,
    title: "Work Tasks",
    description: "Tasks for a productive workday",
    createdOn: new Date(),
    priority: 20,
    labels: ["Productive", "Work"],
    remark: "This is a work tasks category.",
    tasks: [
      {
        id: 3,
        title: "Check emails",
        status: "Not Started",
        description: "Review and respond to emails",
        subtasks: [],
        priorityLabel: "High",
        priority: 30,
        scheduled: { deploymentSchedule: new Date() },
        locked: false,
        flexible: false,
        track: { trackerId: 0, trackerTitle: "", trackerFrequency: "Daily" },
        createdOn: new Date(),
        expiresOn: new Date(),
        completedOn: undefined,
        viewAs: "Status",
        SpecialLabels: ["Urgent"],
        remark: "",
      },
      {
        id: 4,
        title: "Attend team meeting at 10:00 AM",
        status: "Not Started",
        description: "Participate in the team discussion",
        subtasks: [],
        priorityLabel: "High",
        priority: 40,
        scheduled: { deploymentSchedule: new Date() },
        locked: false,
        flexible: false,
        track: { trackerId: 0, trackerTitle: "", trackerFrequency: "Daily" },
        createdOn: new Date(),
        expiresOn: new Date(),
        completedOn: undefined,
        viewAs: "Status",
        SpecialLabels: [],
        remark: "",
      },
      // ... other tasks
    ],
  },
  {
    id: 3,
    title: "Exercise",
    description: "Stay active and maintain a healthy lifestyle",
    createdOn: new Date(),
    priority: 30,
    labels: ["Active", "Health"],
    remark: "This is an exercise category.",
    tasks: [
      {
        id: 5,
        title: "Go for a 30-minute jog or walk",
        status: "Not Started",
        description: "Cardiovascular exercise for overall fitness",
        subtasks: [],
        priorityLabel: "Moderate",
        priority: 50,
        scheduled: { deploymentSchedule: new Date() },
        locked: false,
        flexible: false,
        track: { trackerId: 0, trackerTitle: "", trackerFrequency: "Daily" },
        createdOn: new Date(),
        expiresOn: new Date(),
        completedOn: undefined,
        viewAs: "Status",
        SpecialLabels: [],
        remark: "",
      },
      {
        id: 6,
        title: "Do 15 minutes of stretching or yoga",
        status: "Not Started",
        description: "Improve flexibility and reduce stress",
        subtasks: [],
        priorityLabel: "Moderate",
        priority: 60,
        scheduled: { deploymentSchedule: new Date() },
        locked: false,
        flexible: false,
        track: { trackerId: 0, trackerTitle: "", trackerFrequency: "Daily" },
        createdOn: new Date(),
        expiresOn: new Date(),
        completedOn: undefined,
        viewAs: "Status",
        SpecialLabels: [],
        remark: "",
      },
      // ... other tasks
    ],
  },
  {
    id: 4,
    title: "Household Chores",
    description: "Maintain a clean and organized living space",
    createdOn: new Date(),
    priority: 40,
    labels: ["Clean", "Organize"],
    remark: "This is a household chores category.",
    tasks: [
      {
        id: 7,
        title: "Vacuum the living room",
        status: "Not Started",
        description: "Keep the living space tidy",
        subtasks: [],
        priorityLabel: "Moderate",
        priority: 70,
        scheduled: { deploymentSchedule: new Date() },
        locked: false,
        flexible: false,
        track: { trackerId: 0, trackerTitle: "", trackerFrequency: "Daily" },
        createdOn: new Date(),
        expiresOn: new Date(),
        completedOn: undefined,
        viewAs: "Checkbox",
        SpecialLabels: [],
        remark: "",
      },
      {
        id: 8,
        title: "Do the dishes",
        status: "Not Started",
        description: "Keep the kitchen clean and organized",
        subtasks: [],
        priorityLabel: "Moderate",
        priority: 80,
        scheduled: { deploymentSchedule: new Date() },
        locked: false,
        flexible: false,
        track: { trackerId: 0, trackerTitle: "", trackerFrequency: "Daily" },
        createdOn: new Date(),
        expiresOn: new Date(),
        completedOn: undefined,
        viewAs: "Checkbox",
        SpecialLabels: [],
        remark: "",
      },
      // ... other tasks
    ],
  },
  // ... other categories
];

export default dummyChoresList;
